<?php if ($this->getFaqCategoriesList()): ?>
    <div class="block block-faq-category">
        <div class="block-title">
            <strong><?php echo __('FAQ Categories'); ?></strong>
        </div>
        <div class="block-content">
            <ol class="items">
                <?php foreach($this->getFaqCategoriesList() as $fclist): ?>
                    <li class="item">
                        <a href="<?php echo $this->getUrlCate($fclist['id']);?>">
                            <?php echo __($fclist['name']." Category"); ?> <span class="count">(<?php echo $this->count($fclist['id']); ?>)</span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>

